# frozen_string_literal: true

source 'https://rubygems.org'

gem 'jekyll', '3.9.2'
gem 'jekyll-plantuml', path: '../..'
gem 'kramdown', '2.4.0'
gem 'kramdown-parser-gfm', '1.1.0'
gem 'liquid', '4.0.4'
