# frozen_string_literal: true

# SPDX-FileCopyrightText: Copyright (c) 2014-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT

source 'https://rubygems.org'

gem 'jekyll', '4.4.1'
gem 'jekyll-plantuml', path: '../..'
gem 'kramdown', '2.5.1'
gem 'kramdown-parser-gfm', '1.1.0'
gem 'liquid', '5.11.0'
